kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: ts
  name: user-network-delay
spec:
  selector:
    namespaces:
      - ts
    labelSelectors:
      app: ts-user-service
  mode: one
  action: delay
  duration: 5m
  delay:
    latency: 5s
  direction: both