kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: ts
  name: basic-stress-cpu
spec:
  selector:
    namespaces:
      - ts
    labelSelectors:
      app: ts-basic-service
  mode: one
  stressors:
    cpu:
      workers: 4
      load: 100
  duration: 5m