kind: httpChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: ts
  name: basic-http-outbound
spec:
  selector:
    namespaces:
      - ts
    labelSelectors:
      app: ts-basic-service
  mode: one
  target: Response
  delay: 5s
  port: 15680
  path: "*"
  duration: 5m