kind: httpChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: ts
  name: station-http-outbound
spec:
  selector:
    namespaces:
      - ts
    labelSelectors:
      app: ts-station-service
  mode: one
  target: Response
  delay: 5s
  port: 12345
  path: "*"
  duration: 5m