kind: httpChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: ts
  name: ticketinfo-http-outbound
spec:
  selector:
    namespaces:
      - ts
    labelSelectors:
      app: ts-ticketinfo-service
  mode: one
  target: Response
  delay: 5s
  port: 15681
  path: "*"
  duration: 5m