kind: httpChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: ts
  name: travel-plan-http-outbound
spec:
  selector:
    namespaces:
      - ts
    labelSelectors:
      app: ts-travel-plan-service
  mode: one
  target: Response
  delay: 5s
  port: 14322
  path: "*"
  duration: 5m