kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: ts
  name: user-http-outbound
spec:
  selector:
    namespaces:
      - ts
    labelSelectors:
      app: ts-user-service
  mode: one
  target: Response
  delay: 5s
  port: 12342
  path: "*"
  duration: 5m